modLoader="javafml"
loaderVersion="[1.21.4,)"  # Set the Forge version range for Minecraft 1.21.4
license="MIT"  # Choose a license that fits your mod
[[mods]]
modId="un_gunoi_de_mod"  # Replace with your actual mod ID
version="1.0.0"  # Replace with your mod version
displayName="UnModGunoias"
authors="Razvan"
description='''
A mod that adds new items and features.
'''
[[dependencies.un_gunoi_de_mod]]
modId="forge"
mandatory=true
versionRange="[1.21.4,)"  # Ensure this matches your Minecraft version
ordering="NONE"
side="BOTH"

[[dependencies.un_gunoi_de_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
